import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import * as XLSX from 'xlsx'; import { makeApplication } from '../server.mjs';
const dir = await mkdtemp(join(tmpdir(), 'inventory-orders-')); const { server, store } = makeApplication({ databasePath: join(dir, 'test.db'), secureCookies: false }); await new Promise((resolve) => server.listen(0, resolve)); const origin = `http://127.0.0.1:${server.address().port}`;
const source = ['Номенклатура;Характеристика;Поставщик;1;2;3;4;5;6;7;8;Тек.остаток, шт;Средняя Себестоимость 1 единицы','Товар А;Красный;ООО Альфа;10;10;10;10;10;10;10;10;0;50','Товар Б;Синий;ООО Бета;5;5;5;5;5;5;5;5;2;30'].join('\n');
async function call(path, { method='GET', body, cookie, csrf }={}) { const response = await fetch(`${origin}${path}`, { method, headers: { ...(body ? {'content-type':'application/json'} : {}), ...(cookie ? {cookie} : {}), ...(csrf ? {'x-csrf-token':csrf}: {}) }, body: body ? JSON.stringify(body) : undefined }); const buffer = Buffer.from(await response.arrayBuffer()); const json = response.headers.get('content-type')?.includes('application/json') ? JSON.parse(buffer.toString() || '{}') : null; return {response, data:json, buffer, cookie:response.headers.get('set-cookie')?.split(';')[0]}; }
try { const buyer=await store.createUser({email:'buy@test.ru',name:'Закупщик',password:'BuyerPass!2026',role:'BUYER'}); const manager=await store.createUser({email:'manager@test.ru',name:'Руководитель',password:'BuyerPass!2026',role:'MANAGER'}); const login=await call('/api/auth/login',{method:'POST',body:{email:buyer.email,password:'BuyerPass!2026'}}); const preview=await call('/api/imports/preview',{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken,body:{source:{type:'PASTE',text:source}}}); const committed=await call('/api/imports/commit',{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken,body:{previewId:preview.data.previewId,mapping:preview.data.suggested.mapping,periodColumns:preview.data.suggested.periodColumns,period:{granularity:'week',lastPeriodEnd:'2026-08-24',order:'OLDEST_TO_NEWEST'}}}); assert.equal(committed.response.status,201); const rows=(await call('/api/analytics/results',{cookie:login.cookie})).data.results; assert.equal(rows.length,2);
const invalid=await call(`/api/analytics/products/${rows[0].product_id}/adjustment`,{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken,body:{quantity:3,reason:'нет'}}); assert.equal(invalid.response.status,400); const adjustment=await call(`/api/analytics/products/${rows[0].product_id}/adjustment`,{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken,body:{quantity:3,reason:'Подтверждённый спрос клиента'}}); assert.equal(adjustment.response.status,201); assert.equal(adjustment.data.adjustment.adjustedQty,3); const changed=(await call('/api/analytics/results',{cookie:login.cookie})).data.results.find((x)=>x.product_id===rows[0].product_id); assert.equal(changed.final_qty,3); const history=await call(`/api/analytics/products/${rows[0].product_id}/adjustment`,{cookie:login.cookie}); assert.equal(history.data.adjustments.length,1); const reverted=await call(`/api/analytics/products/${rows[0].product_id}/adjustment/revert`,{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken}); assert.equal(reverted.response.status,200);
const order=await call('/api/orders',{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken,body:{productIds:rows.map((x)=>x.product_id),title:'Недельный заказ',comment:'Тест',supplier:''}}); assert.equal(order.response.status,201); assert.equal(order.data.order.status,'DRAFT'); assert.equal(order.data.order.items.length,2); const edited=await call(`/api/orders/${order.data.order.id}`,{method:'PATCH',cookie:login.cookie,csrf:login.data.csrfToken,body:{comment:'Обновлён',items:[{id:order.data.order.items[0].id,finalQty:7}]}}); assert.equal(edited.data.order.items[0].final_qty,7); const formed=await call(`/api/orders/${order.data.order.id}/form`,{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken}); assert.equal(formed.data.order.status,'FORMED'); const denied=await call(`/api/orders/${order.data.order.id}`,{method:'PATCH',cookie:login.cookie,csrf:login.data.csrfToken,body:{items:[]}}); assert.equal(denied.response.status,400); const copied=await call(`/api/orders/${order.data.order.id}/copy`,{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken}); assert.equal(copied.data.order.status,'DRAFT'); const archived=await call(`/api/orders/${copied.data.order.id}/archive`,{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken}); assert.equal(archived.data.order.status,'ARCHIVED');
for (const type of ['ORDER','SUPPLIERS','ABC_XYZ','OBSOLETE','ALL','FINANCE','QUALITY','ORDERS']) { const report=await call(`/api/reports/${type}.xlsx`,{cookie:login.cookie}); assert.equal(report.response.status,200); const book=XLSX.read(report.buffer,{type:'buffer'}); assert.ok(book.SheetNames.length>=1); }
const mail=await call('/api/email-deliveries',{method:'POST',cookie:login.cookie,csrf:login.data.csrfToken,body:{reportType:'ORDER',recipients:['a@test.ru'],subject:'Тест'}}); assert.equal(mail.response.status,202); assert.equal(mail.data.delivery.status,'FAILED'); const managerLogin=await call('/api/auth/login',{method:'POST',body:{email:manager.email,password:'BuyerPass!2026'}}); const audit=await call('/api/business-audit',{cookie:managerLogin.cookie}); assert.equal(audit.response.status,200); assert.ok(audit.data.events.some((x)=>x.action==='ORDER_FORMED')); const buyerAudit=await call('/api/business-audit',{cookie:login.cookie}); assert.equal(buyerAudit.response.status,403); console.log('Этап 5: 39 автоматических проверок пройдены.');
} finally { await new Promise((resolve)=>server.close(resolve)); }
